In [1]:
#1. Demonstrate three different methods for creating identical 2D arrays in NumPy. Provide the code for each
#method and the final output after each method.

In [2]:
import numpy as np

# Method 1: Using numpy.array()
array1 = np.array([[1, 2, 3], [4, 5, 6]])
print("Method 1:\n", array1)

Method 1:
 [[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np

# Method 2: Using numpy.ones() and modifying
array2 = np.ones((2, 3), dtype=int) * 1  # Create a 2x3 array of ones and multiply by 1
array2[0, 1:] = [2, 3]  # Modify the first row
array2[1, :] = [4, 5, 6]  # Modify the second row
print("Method 2:\n", array2)

Method 2:
 [[1 2 3]
 [4 5 6]]


In [4]:
import numpy as np

# Method 3: Using numpy.full()
array3 = np.full((2, 3), 0)
array3[0] = [1, 2, 3]
array3[1] = [4, 5, 6]
print("Method 3:\n", array3)

Method 3:
 [[1 2 3]
 [4 5 6]]


In [5]:
#2. Using the Numpy function, generate an array of 100 evenly spaced numbers between 1 and 10 and Reshape that 1D array into a 2D array.

In [6]:
import numpy as np

# Generate 100 evenly spaced numbers between 1 and 10
array_1d = np.linspace(1, 10, 100)

# Reshape the 1D array into a 2D array with shape (10, 10)
array_2d = array_1d.reshape((10, 10))

print("2D array:\n", array_2d)


2D array:
 [[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
   1.54545455  1.63636364  1.72727273  1.81818182]
 [ 1.90909091  2.          2.09090909  2.18181818  2.27272727  2.36363636
   2.45454545  2.54545455  2.63636364  2.72727273]
 [ 2.81818182  2.90909091  3.          3.09090909  3.18181818  3.27272727
   3.36363636  3.45454545  3.54545455  3.63636364]
 [ 3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
   4.27272727  4.36363636  4.45454545  4.54545455]
 [ 4.63636364  4.72727273  4.81818182  4.90909091  5.          5.09090909
   5.18181818  5.27272727  5.36363636  5.45454545]
 [ 5.54545455  5.63636364  5.72727273  5.81818182  5.90909091  6.
   6.09090909  6.18181818  6.27272727  6.36363636]
 [ 6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
   7.          7.09090909  7.18181818  7.27272727]
 [ 7.36363636  7.45454545  7.54545455  7.63636364  7.72727273  7.81818182
   7.90909091  8.          8.09090909  8.1818181

In [7]:
#3. The difference in np.array, np.asarray and np.asanyarray.

In [8]:
#3. The difference between Deep copy and shallow copy. 

In [9]:
#4. Generate a 3x3 array with random floating-point numbers between 5 and 20 then, round each number in the array to 2 decimal places.

In [10]:
import numpy as np

# Step 1: Generate a 3x3 array with random floating-point numbers between 5 and 20
random_array = np.random.uniform(5, 20, size=(3, 3))

# Step 2: Round each number in the array to 2 decimal places
rounded_array = np.round(random_array, decimals=2)

print("Random array:\n", random_array)
print("Rounded array:\n", rounded_array)

Random array:
 [[ 8.64567315 10.18552438 19.3330738 ]
 [12.93107495 14.79524871 10.15761061]
 [ 7.98927276 19.98768009 11.92222936]]
Rounded array:
 [[ 8.65 10.19 19.33]
 [12.93 14.8  10.16]
 [ 7.99 19.99 11.92]]


In [11]:
#5. Create a NumPy array with random integers between 1 and 10 of shape (5,6 )). After creating the array perform the following operations: 

# a)Extract all even integers from array.

# b)Extract all odd integers from array.

In [12]:
import numpy as np

# Step 1: Create a NumPy array with random integers between 1 and 10 with shape (5, 6)
array = np.random.randint(1, 11, size=(5, 6))

# Display the original array
print("Original array:\n", array)

# Step 2: Extract all even integers from the array
even_integers = array[array % 2 == 0]

# Display the even integers
print("Even integers:\n", even_integers)


Original array:
 [[ 1  6  6  9  2  2]
 [ 9  3  3  4  3  6]
 [ 7 10  8  9  8 10]
 [ 2  3  1  1  1  8]
 [ 3  7  3  8  9  4]]
Even integers:
 [ 6  6  2  2  4  6 10  8  8 10  2  8  8  4]


In [13]:
import numpy as np

# Step 1: Create a NumPy array with random integers between 1 and 10 with shape (5, 6)
array = np.random.randint(1, 11, size=(5, 6))

# Display the original array
print("Original array:\n", array)

# Step 2: Extract all odd integers from the array
odd_integers = array[array % 2 != 0]

# Display the odd integers
print("Odd integers:\n", odd_integers)

Original array:
 [[ 6 10  2 10  1  3]
 [10  6 10  6  6  3]
 [ 2  8 10  3  4  7]
 [ 4  4  6 10  2  1]
 [ 2  7  7  9  1 10]]
Odd integers:
 [1 3 3 3 7 1 7 7 9 1]


In [14]:
#6. Create a 3D NumPy array of shape (3, 3, 3) containing random integers between 1 and 10. Perform the following operations: 

# a) Find the indices of the maximum values along each depth level (third axis).

# b) Perform element-wise multiplication of between both array.

In [15]:
import numpy as np

# Create a 3D NumPy array of shape (3, 3, 3) containing random integers between 1 and 10
array = np.random.randint(1, 11, size=(3, 3, 3))

# Dsplay the original array
print("Original array:\n", array)

# Find the indices of the maximum values along each depth level (third axis)
# The result will be a 2D array where each element represents the index of the max value along axis=2
max_indices = np.argmax(array, axis=2)

print("Indices of the maximum values along each depth level:\n", max_indices)

Original array:
 [[[ 4  6  1]
  [ 5  7  9]
  [10  8  5]]

 [[ 5  2  4]
  [ 7  2  3]
  [10  5 10]]

 [[ 2  4  4]
  [ 1  7  6]
  [ 4  3  6]]]
Indices of the maximum values along each depth level:
 [[1 2 0]
 [0 0 0]
 [1 1 2]]


In [16]:
import numpy as np

# Step 1: Create a 3D NumPy array of shape (3, 3, 3) containing random integers between 1 and 10
array = np.random.randint(1, 11, size=(3, 3, 3))

# Display the original array
print("Original array:\n", array)

# Step 2: Perform element-wise multiplication between the array and itself
elementwise_multiplication = array * array

# Display the result of the element-wise multiplication
print("Element-wise multiplication of the array with itself:\n", elementwise_multiplication)

Original array:
 [[[ 8  1  5]
  [ 8  3  8]
  [ 7  3  1]]

 [[10 10  7]
  [ 4  5  1]
  [ 8  5  4]]

 [[ 6  5 10]
  [ 6  9  2]
  [ 4  5  5]]]
Element-wise multiplication of the array with itself:
 [[[ 64   1  25]
  [ 64   9  64]
  [ 49   9   1]]

 [[100 100  49]
  [ 16  25   1]
  [ 64  25  16]]

 [[ 36  25 100]
  [ 36  81   4]
  [ 16  25  25]]]


In [20]:
import pandas as pd
df=pd.read_csv("People Data.csv")

In [21]:
df

Index          User Id First Name Last Name  Gender  \
0        1  8717bbf45cCDbEe     Shelia   Mahoney    Male   
1        2  3d5AD30A4cD38ed         Jo    Rivers  Female   
2        3  810Ce0F276Badec     Sheryl    Lowery  Female   
3        4  BF2a889C00f0cE1    Whitney    Hooper    Male   
4        5  9afFEafAe1CBBB9    Lindsey      Rice  Female   
..     ...              ...        ...       ...     ...   
995    996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
996    997  ECddaFEDdEc4FAB      Donna     Barry  Female   
997    998  2adde51d8B8979E      Cathy  Mckinney  Female   
998    999  Fb2FE369D1E171A   Jermaine    Phelps    Male   
999   1000  8b756f6231DDC6e        Lee      Tran  Female   

                             Email                  Phone Date of birth  \
0              pwarner@example.org           857.139.8239    27-01-2014   
1    fergusonkatherine@example.net                    NaN    26-07-1931   
2              fhoward@example.org          (599)782-0605    25-11-2013   
3            zjohnston@example.com                    NaN    17-11-2012   
4                 elin@example.net     (390)417-1635x3010    15-04-1923   
..                             ...                    ...           ...   
995         lyonsdaisy@example.net           021.775.2933    05-01-1959   
996        dariusbryan@example.com   001-149-710-7799x721    06-10-2001   
997         georgechan@example.org  +1-750-774-4128x33265    13-05-1918   
998            wanda04@example.net          (915)292-2254    31-08-1971   
999        deannablack@example.org     079.752.5424x67259    24-01-1947   

                           Job Title  Salary  
0                  Probation officer   90000  
1                             Dancer   80000  
2                               Copy   50000  
3           Counselling psychologist   65000  
4                Biomedical engineer  100000  
..                               ...     ...  
995                Personnel officer   90000  
996          Education administrator   50000  
997  Commercial/residential surveyor   60000  
998                 Ambulance person  100000  
999       Nurse, learning disability   90000  

[1000 rows x 10 columns]

In [23]:
#7. Clean and transform the 'Phone' column in the sample dataset to remove non-numeric characters and 
#convert it to a numeric data type. Also display the table attributes and data types of each column.

In [24]:
# Create DataFrame
df1 = pd.DataFrame(df)

# Display the original DataFrame
print("Original DataFrame:")
print(df1)

# Step 1: Remove non-numeric characters from the 'Phone' column
df1['Phone'] = df1['Phone'].replace(to_replace=r'\D', value='', regex=True)

# Step 2: Convert the cleaned 'Phone' column to numeric data type
# This step converts the 'Phone' column to integers
df1['Phone'] = pd.to_numeric(df1['Phone'])

# Display the cleaned DataFrame
print("\nCleaned DataFrame:")
print(df1)

# Step 3: Display the table attributes and data types of each column
print("\nData types of each column:")
print(df1.dtypes)


Original DataFrame:
     Index          User Id First Name Last Name  Gender  \
0        1  8717bbf45cCDbEe     Shelia   Mahoney    Male   
1        2  3d5AD30A4cD38ed         Jo    Rivers  Female   
2        3  810Ce0F276Badec     Sheryl    Lowery  Female   
3        4  BF2a889C00f0cE1    Whitney    Hooper    Male   
4        5  9afFEafAe1CBBB9    Lindsey      Rice  Female   
..     ...              ...        ...       ...     ...   
995    996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
996    997  ECddaFEDdEc4FAB      Donna     Barry  Female   
997    998  2adde51d8B8979E      Cathy  Mckinney  Female   
998    999  Fb2FE369D1E171A   Jermaine    Phelps    Male   
999   1000  8b756f6231DDC6e        Lee      Tran  Female   

                             Email                  Phone Date of birth  \
0              pwarner@example.org           857.139.8239    27-01-2014   
1    fergusonkatherine@example.net                    NaN    26-07-1931   
2              fhoward@example.org

In [25]:
#8. Perform the following tasks using people dataset: 

# a) Read the 'data.csv' file using pandas, skipping the first 50 rows. 

# b) Only read the columns: 'Last Name', ‘Gender’,’Email’,‘Phone’ and ‘Salary’ from the file.

# c) Display the first 10 rows of the filtered dataset.

# d) Extract the ‘Salary’' column as a Series and display its last 5 values.

In [30]:
# Step a: Read the 'data.csv' file using pandas, skipping the first 50 rows
import pandas as pd

# Step a: Read the 'data.csv' file using pandas, skipping the first 50 rows
df = pd.read_csv('People Data.csv', skiprows=50)

# Step: Check the column names and data to ensure correct reading
print("Column names in the DataFrame:")
print(df.columns)

# Strip any leading or trailing spaces from column names
df.columns = df.columns.str.strip()

# Step b: Only read the specified columns, ensuring column names are correct
try:
    df_filtered = df[['Last Name', 'Gender', 'Email', 'Phone', 'Salary']]
except KeyError as e:
    print(f"Error: {e}")
    print("Check column names and ensure they match exactly.")

# Display the first 10 rows of the filtered dataset
print("\nFirst 10 rows of the filtered dataset:")
print(df_filtered.head(10))

# Step d: Extract the 'Salary' column as a Series and display its last 5 values
salary_series = df_filtered['Salary']
print("\nLast 5 values of the 'Salary' column:")
print(salary_series.tail(5))


Column names in the DataFrame:
Index(['50', 'afF3018e9cdd1dA', 'George', 'Mercer', 'Female',
       'douglascontreras@example.net', '+1-326-669-0118x4341', '11-09-1941',
       'Human resources officer', '70000'],
      dtype='object')
Error: "None of [Index(['Last Name', 'Gender', 'Email', 'Phone', 'Salary'], dtype='object')] are in the [columns]"
Check column names and ensure they match exactly.

First 10 rows of the filtered dataset:


NameError: name 'df_filtered' is not defined

In [31]:
#9. Filter and select rows from the People_Dataset, where the “Last Name' column contains the name 'Duke',  'Gender' column contains the word Female and ‘Salary’ should be less than 85000

In [33]:
import pandas as pd

# Step 1: Read the dataset from the CSV file
df = pd.read_csv('People Data.csv', skiprows=50)

# Strip any leading or trailing spaces from column names
df.columns = df.columns.str.strip()

# Step 2: Filter rows based on conditions
# Ensure that 'Last Name' contains 'Duke', 'Gender' contains 'Female', and 'Salary' is less than 85000
filtered_df = df[
    (df['Last Name'].str.contains('Duke', case=False, na=False)) &
    (df['Gender'].str.contains('Female', case=False, na=False)) &
    (df['Salary'] < 85000)
]

# Display the filtered DataFrame
print("Filtered DataFrame:")
print(filtered_df)


KeyError: 'Last Name'